# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pwsqr"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Smile @rT"]
  s.date = "2012-11-19"
  s.description = "This gem helps you securely and easily copy passwords from terminal pws tool, to your mobile devices using QR codes."
  s.email = "smileart21@gmail.com"
  s.executables = ["pwsqr"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/pwsqr",
    "lib/pwsqr.rb",
    "pwsqr.gemspec",
    "test/helper.rb",
    "test/test_pwsqr.rb"
  ]
  s.homepage = "http://github.com/smileart/pwsqr"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simple QR interface to pws gem, to easily use your passwords on a smartphone!"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<clipboard>, [">= 0"])
      s.add_runtime_dependency(%q<clamp>, [">= 0"])
      s.add_runtime_dependency(%q<onetime>, [">= 0"])
      s.add_runtime_dependency(%q<qrcli>, [">= 0"])
      s.add_runtime_dependency(%q<pws>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<awesome_print>, [">= 0"])
    else
      s.add_dependency(%q<clipboard>, [">= 0"])
      s.add_dependency(%q<clamp>, [">= 0"])
      s.add_dependency(%q<onetime>, [">= 0"])
      s.add_dependency(%q<qrcli>, [">= 0"])
      s.add_dependency(%q<pws>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
    end
  else
    s.add_dependency(%q<clipboard>, [">= 0"])
    s.add_dependency(%q<clamp>, [">= 0"])
    s.add_dependency(%q<onetime>, [">= 0"])
    s.add_dependency(%q<qrcli>, [">= 0"])
    s.add_dependency(%q<pws>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
  end
end

